name: Link Checker

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  link-checker:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Link Checker
        uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332 # v2.4.1
        with:
          args: --base . --verbose --no-progress --exclude-path '\.github' './**/*.md'
